ECHO Compiling...
iverilog -o my_design one_wire_GC_intf.v gc_cmd_handler.v tactile_sw_debouncer.v gc_cont_top.v controller_sim.v
ECHO Executing...
vvp my_design -n -v
ECHO Output Waveform...
gtkwave gc_simout.vcd -a waves.gtkw